import { ChallengeDef } from '../types';

export const CHALLENGE_DEFS: ChallengeDef[] = [
  {
    id: 'five-week',
    name: '5 Rides This Week',
    description: 'Log 5 rides within any 7-day window',
    icon: 'calendar',
    type: 'rides',
    target: 5,
    durationDays: 7,
  },
  {
    id: 'monthly-warrior',
    name: 'Monthly Warrior',
    description: 'Log 20 rides in 30 days',
    icon: 'calendar',
    type: 'rides',
    target: 20,
    durationDays: 30,
  },
  {
    id: 'five-hours',
    name: '5-Hour Challenge',
    description: 'Accumulate 5 hours (300 min) of riding',
    icon: 'clock',
    type: 'duration',
    target: 300,
  },
  {
    id: 'streak-14',
    name: '2-Week Streak',
    description: 'Ride every day for 14 days straight',
    icon: 'flame',
    type: 'streak',
    target: 14,
  },
  {
    id: 'fifty-km-week',
    name: '50 km Week',
    description: 'Ride 50 km within 7 days',
    icon: 'route',
    type: 'distance',
    target: 50,
    durationDays: 7,
  },
  {
    id: 'ten-rides-row',
    name: 'Ten Straight',
    description: 'Log 10 rides in 10 consecutive days',
    icon: 'lightning',
    type: 'streak',
    target: 10,
  },
  {
    id: 'calorie-crusher',
    name: 'Calorie Crusher',
    description: 'Burn 2,000 calories total',
    icon: 'flame',
    type: 'calories',
    target: 2000,
  },

  // ─── Real-World Event Challenges ─────────────────────────────────────────────

  {
    id: 'etape-du-tour',
    name: "L'Étape du Tour",
    description: 'Ride a full Tour de France stage — 165 km cumulative',
    icon: 'flag',
    type: 'distance',
    target: 165,
  },
  {
    id: 'paris-roubaix',
    name: 'Paris-Roubaix',
    description: 'Conquer the Hell of the North — 257 km cumulative',
    icon: 'mountain',
    type: 'distance',
    target: 257,
  },
  {
    id: 'seattle-to-portland',
    name: 'Seattle to Portland',
    description: 'The iconic PNW ride — 323 km cumulative',
    icon: 'tree',
    type: 'distance',
    target: 323,
  },
  {
    id: 'unbound-gravel',
    name: 'Unbound Gravel',
    description: "America's premier gravel race — 354 km cumulative",
    icon: 'tree',
    type: 'distance',
    target: 354,
  },
  {
    id: 'vuelta-a-espana',
    name: 'Vuelta a España',
    description: 'All 21 stages through Spain — 3,272 km cumulative',
    icon: 'flag',
    type: 'distance',
    target: 3272,
  },
  {
    id: 'tour-de-france',
    name: 'Tour de France',
    description: 'The greatest race on Earth — 3,357 km cumulative',
    icon: 'trophy',
    type: 'distance',
    target: 3357,
  },
  {
    id: 'giro-ditalia',
    name: "Giro d'Italia",
    description: 'The beautiful Italian Grand Tour — 3,445 km cumulative',
    icon: 'flag',
    type: 'distance',
    target: 3445,
  },
];
