import { ChallengeDef } from '../types';

export const RUNNING_CHALLENGE_DEFS: ChallengeDef[] = [
  {
    id: 'five-runs-week',
    name: '5 Runs This Week',
    description: 'Log 5 runs within any 7-day window',
    icon: 'calendar',
    type: 'rides',
    target: 5,
    durationDays: 7,
  },
  {
    id: 'monthly-warrior',
    name: 'Monthly Warrior',
    description: 'Log 20 runs in 30 days',
    icon: 'calendar',
    type: 'rides',
    target: 20,
    durationDays: 30,
  },
  {
    id: 'five-hours',
    name: '5-Hour Challenge',
    description: 'Accumulate 5 hours (300 min) of running',
    icon: 'clock',
    type: 'duration',
    target: 300,
  },
  {
    id: 'streak-14',
    name: '2-Week Streak',
    description: 'Run every day for 14 days straight',
    icon: 'flame',
    type: 'streak',
    target: 14,
  },

  // ─── Real-World Race Challenges ───────────────────────────────────────────────

  {
    id: 'five-k',
    name: '5K',
    description: 'Run a 5K — 5 km cumulative',
    icon: 'medal',
    type: 'distance',
    target: 5,
  },
  {
    id: 'ten-k',
    name: '10K',
    description: 'Run a 10K — 10 km cumulative',
    icon: 'medal',
    type: 'distance',
    target: 10,
  },
  {
    id: 'half-marathon',
    name: 'Half Marathon',
    description: 'Run a half marathon — 21.1 km cumulative',
    icon: 'medal',
    type: 'distance',
    target: 21.1,
  },
  {
    id: 'marathon',
    name: 'Marathon',
    description: 'Conquer 26.2 miles — 42.2 km cumulative',
    icon: 'trophy',
    type: 'distance',
    target: 42.2,
  },
  {
    id: 'fifty-k-ultra',
    name: '50K Ultra',
    description: 'Your first ultra — 50 km cumulative',
    icon: 'muscle',
    type: 'distance',
    target: 50,
  },
  {
    id: 'hundred-mile-week',
    name: '100-Mile Week',
    description: 'Run 100 miles (161 km) in 7 days',
    icon: 'globe',
    type: 'distance',
    target: 160.9,
    durationDays: 7,
  },
  {
    id: 'boston-marathon',
    name: 'Boston Marathon',
    description: 'Run the Boston Marathon route — 42.2 km cumulative',
    icon: 'flag',
    type: 'distance',
    target: 42.2,
  },
  {
    id: 'western-states',
    name: 'Western States 100',
    description: 'Conquer the legendary ultra — 161 km cumulative',
    icon: 'mountain',
    type: 'distance',
    target: 161,
  },
  {
    id: 'comrades-ultra',
    name: 'Comrades Ultra',
    description: "South Africa's iconic ultra — 90 km cumulative",
    icon: 'globe',
    type: 'distance',
    target: 90,
  },
  {
    id: 'utmb',
    name: 'UTMB',
    description: 'Ultra-Trail du Mont-Blanc — 171 km cumulative',
    icon: 'mountain',
    type: 'distance',
    target: 171,
  },
];
